### ISSUE TITLE
python-memchached raise pyuv.Timer object has no attribute 'unref' exception

### ISSUE THREAD

**Issue by jiangjianxiao** [saghul/uvent#2]
https://github.com/linsomniac/python-memcached

```
import memcache
mc = memcache.Client( ['127.0.0.1:11211'], debug=0)

mc.get('mykey') # raise exception

--------------
os: windows
gevent 1.0 rc2
pyuv build from master branch
```

**Comment by saghul** [comment]
Can you paste the traceback?

**Comment by jiangjianxiao** [comment]
sorry. tracback is:

```

[E 130802 15:40:34 api:78] Traceback (most recent call last):
      File "C:\Works\yarder\yarder\yarder\api.py", line 75, in get_cache
        result = mc.get(_key)
      File "C:\Users\jiang\Envs\c9\lib\site-packages\memcache.py", line 888, in get
        return self._get('get', key)
      File "C:\Users\jiang\Envs\c9\lib\site-packages\memcache.py", line 838, in _get
        server, key = self._get_server(key)
      File "C:\Users\jiang\Envs\c9\lib\site-packages\memcache.py", line 354, in _get_server
        if server.connect():
      File "C:\Users\jiang\Envs\c9\lib\site-packages\memcache.py", line 1111, in connect
        if self._get_socket():
      File "C:\Users\jiang\Envs\c9\lib\site-packages\memcache.py", line 1130, in _get_socket
        s.connect(self.address)
      File "build\bdist.win32\egg\gevent\socket.py", line 347, in connect
        self._wait(self._write_event)
      File "build\bdist.win32\egg\gevent\socket.py", line 294, in _wait
        timeout = Timeout.start_new(self.timeout, timeout_exc, ref=False)
      File "build\bdist.win32\egg\gevent\timeout.py", line 119, in start_new
        timeout.start()
      File "build\bdist.win32\egg\gevent\timeout.py", line 100, in start
        self.timer.start(getcurrent().throw, self.exception)
      File "build\bdist.win32\egg\uvent\loop.py", line 375, in start
        self._handle.unref()
    AttributeError: 'pyuv.Timer' object has no attribute 'unref'
```

**Comment by saghul** [comment]
Ah, I remember. I removed ref() and unref() in pyuv master, ref is now a property. You should use pyuv 0.10 branch until 0.12 is released, since some of my projects will need updating then.

**Comment by jiangjianxiao** [comment]
thanks, use v.10 branch is work fine.

**Comment by alanjds** [comment]
Is it working with `pyuv>=1.0`? Tested here and looks bad.
